export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
    somethingWentWrong: 'Something went wrong. Please after sometime.',
  },
  // home: {
  //   header: 'Home',
  //   message: 'Welcome',
  //   variant: 'App variant: ',
  // },
  register: {
    username: 'Username',
    usernameHint: 'Enter your name',
    usermobile: 'usermobile',
    usermobileHint: 'Enter your mobile',
    useremail: 'useremail',
    useremailHint: 'Enter your email',
    button: 'Register',
    submit: 'Submit',
    password: 'Password',
    passwordHint: 'Enter your password',
    imageUploadFailed: 'Failed to upload user image',
  },
  login: {
    username: 'name',
    usernameHint: 'Enter your name',
    button: 'Login',
    submit: 'Submit',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid credentials',
    imageDownoadFailed: 'Failed to download user image',
    imageUploadFailed: 'Failed to upload user image',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
};
